name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VARIABLE: data

permissions:
  contents: read

jobs:
  rpios-bullseye-64:
    name: Raspberry Pi OS 11 (64-bit)
    runs-on: ubuntu-20.04
    container: debian:bullseye
    timeout-minutes: 10
    
    env:
      VARIABLE: data

    steps:
    - uses: actions/checkout@v3
      name: Checkout
    - name: Prepare environment
      run: dpkg --add-architecture arm64
    - uses: actions/setup-python@v3
      name: Setup Python
    - name: Install python dependancies
      run: pip install jinja2 ply pyyaml
    - uses: BSFishy/meson-build@v1.0.3
      name: Build Raspberry Pi pipeline and IPA
      with:
        action: build
        meson-version: 0.56
        setup-options: -Dipas=raspberrypi -Dpipelines=raspberrypi
    
